// #391: Property test asserting meets_threshold and record_approval accumulation logic
// never disagree about quorum across randomised weight/threshold inputs.
//
// Two complementary approaches are used:
//
//   1. Table-driven: a large hand-crafted table covering boundary conditions,
//      off-by-one edges, overflow proximity, and varied weight distributions.
//      Each entry drives the same invariant: simulate dedup-accumulation in
//      plain Rust (no Env needed) and verify that meets_threshold first
//      returns `true` at the exact step where accumulated_weight >= threshold.
//
//   2. proptest macro: random (weights, threshold) inputs generated by the
//      proptest engine covering the space not hit by the hand-crafted table.
//
// Invariant under test
// --------------------
// Given a sequence of signer weights [w0, w1, …, wN], simulate the
// record_approval dedup logic:
//
//   - Each signer index is treated as a unique identity.
//   - Once a signer index has been seen, subsequent entries for that index
//     are no-ops (weight is not re-added, list is not grown).
//   - After each step, accumulated_weight is the sum of weights of distinct
//     signers seen so far.
//
// The invariant:
//   meets_threshold(accumulated_weight, threshold) == (accumulated_weight >= threshold)
//
// This must hold for EVERY step, with no off-by-one in either direction.

use multisig::meets_threshold;
use proptest::prelude::*;
use std::collections::HashSet;

// ---------------------------------------------------------------------------
// Core invariant helper
// ---------------------------------------------------------------------------

/// Simulate the dedup-then-accumulate logic of `record_approval` in plain
/// Rust (no Env, no Soroban) and assert the quorum invariant at every step.
///
/// `signer_entries` is a sequence of `(signer_index, weight)` pairs.  The
/// signer_index acts as a stand-in for an `Address` — identical indices model
/// duplicate approvals.
fn assert_quorum_invariant(signer_entries: &[(usize, u32)], threshold: u32) {
    let mut seen: HashSet<usize> = HashSet::new();
    let mut accumulated: u32 = 0;

    for (step, &(signer_idx, weight)) in signer_entries.iter().enumerate() {
        if seen.insert(signer_idx) {
            // New signer — add their weight (saturating to avoid overflow panics
            // in tests; the production code uses checked_add + panic_with_error,
            // but for the invariant we only care about the comparison outcome).
            accumulated = accumulated.saturating_add(weight);
        }
        // Invariant: meets_threshold must agree with plain >= comparison.
        let expected = accumulated >= threshold;
        let actual = meets_threshold(accumulated, threshold);
        assert_eq!(
            actual, expected,
            "quorum disagreement at step {step}: accumulated={accumulated}, \
             threshold={threshold}, expected={expected}, got={actual}"
        );
    }
}

// ---------------------------------------------------------------------------
// Table-driven property tests
// ---------------------------------------------------------------------------

#[test]
fn prop_quorum_first_reached_at_threshold() {
    // Each case: list of (signer_index, weight) pairs, and the threshold.
    // The invariant is verified at every intermediate step.
    let cases: &[(&[(usize, u32)], u32)] = &[
        // ---- trivial / single signer ----
        (&[(0, 1)], 1), // exact: one signer hits threshold
        (&[(0, 1)], 2), // never reaches threshold
        (&[(0, 2)], 1), // overshoots threshold immediately
        (&[(0, 0)], 0), // zero threshold, zero weight
        (&[(0, 1)], 0), // zero threshold, weight=1 (threshold already met before step)
        // ---- two distinct signers ----
        (&[(0, 1), (1, 1)], 2), // reaches threshold exactly on second approval
        (&[(0, 1), (1, 1)], 3), // two signers never reach threshold of 3
        (&[(0, 2), (1, 1)], 2), // first signer already satisfies threshold
        (&[(0, 1), (1, 2)], 2), // second signer pushes over threshold
        // ---- duplicate signers (no-op on repeat) ----
        (&[(0, 3), (0, 3)], 3), // duplicate — weight stays at 3 after step 1
        (&[(0, 1), (0, 1), (1, 2)], 2), // dup then new signer reaches threshold
        (&[(0, 1), (1, 1), (0, 5)], 2), // dup at end; threshold reached at step 2
        // ---- larger sequences ----
        (&[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1)], 3), // reaches threshold at step 3 (0-indexed: after signer 2)
        (&[(0, 10), (1, 10), (2, 10)], 25), // never reaches 25 with 10+10+10=30 — wait, 30 >= 25, so reached at step 3
        (&[(0, 10), (1, 10), (2, 10)], 31), // never reaches 31
        (&[(0, 5), (1, 5), (2, 5), (3, 5)], 20), // reaches exactly at step 4
        // ---- weight distribution variety ----
        (&[(0, 100), (1, 1)], 50), // first signer weight >> threshold
        (&[(0, 1), (1, 100)], 50), // second signer weight >> threshold
        (&[(0, 25), (1, 25), (2, 25), (3, 25)], 100), // evenly distributed, hits at step 4
        // ---- all duplicates except last ----
        (&[(0, 1), (0, 1), (0, 1), (0, 1), (1, 10)], 5), // signer 0 is dup 4x, then signer 1 with weight 10 reaches threshold
        // ---- near u32::MAX territory (saturation) ----
        (&[(0, u32::MAX / 2), (1, u32::MAX / 2)], u32::MAX - 1),
        (&[(0, u32::MAX)], u32::MAX),
        (&[(0, u32::MAX)], 1),
        // ---- empty sequence ----
        (&[], 0), // no signers, threshold 0 — invariant vacuously holds
        (&[], 1), // no signers, threshold 1 — accumulated=0 never reaches 1
    ];

    for (entries, threshold) in cases {
        assert_quorum_invariant(entries, *threshold);
    }
}

/// Verify that duplicate signers do not inflate the accumulated weight.
#[test]
fn prop_duplicate_signers_do_not_inflate_weight() {
    // (signer_index, weight): signer 0 appears 10 times; weight must only
    // be counted once.
    let entries: Vec<(usize, u32)> = (0..10).map(|_| (0usize, 5u32)).collect();
    let threshold = 5u32;

    let mut seen: HashSet<usize> = HashSet::new();
    let mut accumulated: u32 = 0;

    for &(signer_idx, weight) in &entries {
        if seen.insert(signer_idx) {
            accumulated = accumulated.saturating_add(weight);
        }
    }

    // Weight must be exactly 5 (first signer only), not 50.
    assert_eq!(accumulated, 5, "duplicate signers must not inflate weight");
    assert!(
        meets_threshold(accumulated, threshold),
        "weight=5 must satisfy threshold=5"
    );
}

/// Verify meets_threshold boundary: weight == threshold - 1 is false, weight == threshold is true.
#[test]
fn prop_meets_threshold_boundary_conditions() {
    let boundaries: &[(u32, u32, bool)] = &[
        (0, 0, true),
        (0, 1, false),
        (1, 1, true),
        (1, 2, false),
        (2, 2, true),
        (99, 100, false),
        (100, 100, true),
        (101, 100, true),
        (u32::MAX - 1, u32::MAX, false),
        (u32::MAX, u32::MAX, true),
        (u32::MAX, 0, true),
        (u32::MAX, 1, true),
    ];

    for &(weight, threshold, expected) in boundaries {
        assert_eq!(
            meets_threshold(weight, threshold),
            expected,
            "meets_threshold({weight}, {threshold}) should be {expected}"
        );
    }
}

/// Verify quorum invariant over a sweep of monotonically increasing weight sequences.
#[test]
fn prop_monotonic_weight_accumulation_invariant() {
    // For each threshold in 1..=20, build a sequence where each new signer
    // adds exactly 1 unit of weight.  The invariant must hold at every step,
    // and threshold must be satisfied for the first time exactly at step
    // `threshold` (0-indexed: after the threshold-th distinct signer).
    for threshold in 1u32..=20 {
        let entries: Vec<(usize, u32)> = (0..30).map(|i| (i, 1u32)).collect();
        assert_quorum_invariant(&entries, threshold);

        // Confirm the exact step — simulate and find first true.
        let mut acc = 0u32;
        let mut first_true_step: Option<usize> = None;
        for (step, &(_, w)) in entries.iter().enumerate() {
            acc = acc.saturating_add(w);
            if meets_threshold(acc, threshold) && first_true_step.is_none() {
                first_true_step = Some(step);
            }
        }

        assert_eq!(
            first_true_step,
            Some((threshold as usize).saturating_sub(1)),
            "with unit weights, quorum should first be reached at step {} (threshold={})",
            threshold - 1,
            threshold
        );
    }
}

// ---------------------------------------------------------------------------
// proptest macro variant
// ---------------------------------------------------------------------------

proptest! {
    /// Property: for any random (weights, threshold), meets_threshold must
    /// always agree with the plain >= comparison after dedup-accumulation.
    #[test]
    fn prop_meets_threshold_matches_accumulation(
        weights in proptest::collection::vec(1u32..=50u32, 1..=20),
        threshold in 1u32..=100u32,
    ) {
        // Treat each index as a distinct signer (no duplicates in this variant
        // — we separately test duplicate handling above).
        let entries: Vec<(usize, u32)> = weights
            .iter()
            .enumerate()
            .map(|(i, &w)| (i, w))
            .collect();

        assert_quorum_invariant(&entries, threshold);
    }

    /// Property: inserting duplicate signers never changes the accumulated
    /// weight compared to inserting each signer once.
    #[test]
    fn prop_duplicate_insertion_is_idempotent(
        weights in proptest::collection::vec(1u32..=50u32, 1..=10),
        threshold in 1u32..=100u32,
    ) {
        // Build a sequence where every signer appears exactly twice.
        // Weight after dedup should equal the sum of the original weights.
        let deduped_sum: u32 = weights.iter().cloned().fold(0u32, |acc, w| acc.saturating_add(w));

        // Simulate: each signer index 0..n appears twice.
        let entries_with_dups: Vec<(usize, u32)> = weights
            .iter()
            .enumerate()
            .flat_map(|(i, &w)| [(i, w), (i, w)])
            .collect();

        let mut seen: HashSet<usize> = HashSet::new();
        let mut accumulated: u32 = 0;
        for &(idx, w) in &entries_with_dups {
            if seen.insert(idx) {
                accumulated = accumulated.saturating_add(w);
            }
        }

        prop_assert_eq!(
            accumulated, deduped_sum,
            "duplicate signers must not inflate accumulated weight"
        );
        prop_assert_eq!(
            meets_threshold(accumulated, threshold),
            accumulated >= threshold,
            "meets_threshold must agree with >= for accumulated={}, threshold={}",
            accumulated,
            threshold
        );
    }
}
